services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=default
      - POSTGRES_DB=test
#  flask-app:
#    build: backend
#    ports:
#     - "5000:5000"
#    env_file:
#      - backend/.env
#    depends_on:
#      - postgres
#  next-app:
#    build: frontend
#    ports:
#      - "3000:3000"
#    env_file:
#      - frontend/.env
#    depends_on:
#      - flask-app
